version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: dockerfiles/app.dev.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database"

    web:
        build:
            context: .
            dockerfile: dockerfiles/web.dev.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - ${WEB_LISTEN_PORT:-80}:80
            - ${WEB_HTTPS_LISTEN_PORT:-80}:443

    database:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - ${DB_LISTEN_PORT:-3306}:3306
volumes:
    dbdata:
