version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: dockerfiles/app.prod.dockerfile
        working_dir: /var/www
        depends_on:
            - "database"
        volumes:
            - ./.env:/var/www/.env
            - tc-storage:/var/www/storage/app

    web:
        build:
            context: .
            dockerfile: dockerfiles/web.prod.dockerfile
        working_dir: /var/www
        depends_on:
            - "app"
        ports:
            - ${WEB_LISTEN_PORT:-80}:80
            - ${WEB_HTTPS_LISTEN_PORT:-443}:443
        networks:
          default:
          frontend:
            aliases:
              - telesalud-frontend

    database:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ChAnGeThIs
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - ${DB_LISTEN_PORT:-3306}:3306
volumes:
    dbdata:
    tc-storage:

networks:
  # Remove this network and its references if you don't need a reverse-proxy
  frontend:
    external: true
    name: frontend
